### ISSUE TITLE
Adding Linux and Mac OS notification feature

### ISSUE THREAD

**Issue by skate1512** [skate1512/Toggle_Keys_Notification#1]
- Currently, the code only works on Windows. Adding Linux and Mac OS notification feature will make this project better. 

- [ ]  Linux

- [ ] MacOS

**Comment by skate1512** [comment]
Providing Linux and Mac notification scripts in separate files will allow users to download and use only the files that they need. This will allow the usage of OS specific code and packages.

**Comment by Mr-Sunglasses** [comment]
@skate1512 I am working on the linux Script🐧

**Comment by skate1512** [comment]
Splitting this issue into 2 separate issues - #5 and #6
