### ISSUE TITLE
Run the script on startup in Linux 

### ISSUE THREAD

**Issue by rakshit-puri** [skate1512/Toggle_Keys_Notification#12]
Add instructions similar to the ones in README.md for Windows.

**Comment by AKSMA** [comment]
Hi @skate1512 i am new to this and i would like to help with this. Can you elaborate this a bit?

**Comment by rakshit-puri** [comment]
> Hi @skate1512 i am new to this and i would like to help with this. Can you elaborate this a bit?

Hi,
In windows we can setup an application to run at startup directly. 

The requirement in this issue is to have a way to run this script at startup/after login in Linux.

**Comment by AKSMA** [comment]
So basically i have to change the documentation for it.

**Comment by rakshit-puri** [comment]
> So basically i have to change the documentation for it.

If any script needs to be added to make this possible then you need to create that script and modify documentation.

If you find a way to implement this just by following some steps then you can add the steps in the documentation.
