### ISSUE TITLE
Linux notification feature

### ISSUE THREAD

**Issue by rakshit-puri** [skate1512/Toggle_Keys_Notification#5]
Providing Linux notification scripts in a separate file will allow users to download and use only the files they need. It will allow the usage of OS-specific code and packages.

**Comment by kedar-hargude** [comment]
Hey @skate1512, have you closed this issue? I would like to try it out on Linux.

**Comment by rakshit-puri** [comment]
@kedar-hargude This issue is open. Issue #1 was closed and split into issues #5 and #6. PRs are welcome for issues #5 and #6.

**Comment by kedar-hargude** [comment]
I would like to try this out. May you assign this to me @skate1512 ? 

Also, should an issue be assigned to someone to get a hacktoberfest contribution?

**Comment by rakshit-puri** [comment]
When I accept the PR it should be labelled Hacktoberfest accepted.

**Comment by kedar-hargude** [comment]
Hey @skate1512, can you send me your discord link or something? Would like to talk about this issue.

**Comment by rakshit-puri** [comment]
@kedar-hargude We can use the Discussions tab
